baby:
  # BELANGRIJK:
  #   Data moeten in de volgende vorm: JJJJ/MM/DD
  #   Altijd vier cijfers voor jaar, twee cijfers voor maand, en altijd twee cijfers voor dag
  #   Voorbeeld: 2017/07/01

  # Datum dat baby'tje is uitgerekend:
  uitgerekend: 2017/06/29

  # 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶
  # 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶

  # !!!!!! Joeeeee BABY SLABBERS GEBOREN !!!!!!
  # Vul dan de velden hieronder in!
  # (Alleen als alle velden zijn ingevuld wordt de website aangepast.)

  # Datum dat baby'tje is geboren:
  geboren:

  # Naam (bv. Berry):
  naam:

  # Gewicht (bv. 3410 gram):
  gewicht:

  # 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶
  # 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶 👶